### ISSUE TITLE
Replace property grid

### ISSUE THREAD

**Issue by ghost** [QMDevTeam/QMDesigner#3]
This will be developed by Das Global.

As a QM Designer user I want to be able to edit the properties of the objects listed below in a more intuitive way instead of property grid so that the experience is more intuitive for the user. Also, when a property is not relevant I want it to be disabled or invisible Ej. Range validations for open text questions.

Objects:
- Questionnaire sets
- Questionnaire
- Section
- Question
- Checkpoint
- Info screen

**Comment by fredym** [comment]
We also need to replace the property grids in the editors of the "Edit" menu.

**Comment by gerardlopez2001** [comment]
Moved to Trello:  https://trello.com/c/18kmOTKX
