### ISSUE TITLE
Remove concept of variable scope

### ISSUE THREAD

**Issue by ghost** [QMDevTeam/QMDesigner#5]
As a QM Designer user, I don't want to decide where the values are going to be stored.

In the user interface this property will be removed.
In the generator code, the variable scopes will be assigned automatically to the nearest parent container, this means that all questions will be automatically assigned to section level.

Related to QMDevTeam/QMDesigner#34

**Comment by gerardlopez2001** [comment]
Moved to Trello:  https://trello.com/c/eyuSs5KV
