### ISSUE TITLE
Calculated variables / automatic expression calculations.

### ISSUE THREAD

**Issue by ghost** [QMDevTeam/QMDesigner#6]
As a QM Designer user I want to be able to create a calculated value and define it in terms of question variables or other calculated values, I want that the application automatically validate potential issues (loop references, invalid variable names, syntax errors, etc) and to automatically generates the code to update the value when needed and add it to the necessary events.

Related to QMDevTeam/QMGeneral#19

**Comment by gerardlopez2001** [comment]
Moved to Trello: https://trello.com/c/wJCseiFu
