### ISSUE TITLE
Cardinality for groups

### ISSUE THREAD

**Issue by ghost** [QMDevTeam/QMDesigner#8]
I want to limit the times the groups of questions defined in issue #7 can be repeated based on a true/false expression to be evaluated while asking the questions. This condition typically will be defined, but not restricted to, using a flag (when certain question is answered positive) or by counting the number of group instances (when the question group has being asked _n_ times).

**Comment by fredym** [comment]
_n_ can be:
- A constant number
- A number from an expression
- Unlimited

**Comment by fredym** [comment]
The properties we need to describe the group behavior are:
- How many instances we are expecting by design.
- Whether we want to use selection screen.

**Comment by gerardlopez2001** [comment]
Moved to Trello:  https://trello.com/c/4zlOsX2M
